- name: Instalando o pip
  apt:
    name:
      - python-pip

- name: Instalando dependencia do modulo k8s 
  pip:
    name:
      - openshift
      - PyYAML

- name: Copiando o arquivo de deployment da app v1
  template:
    src:  app-v1.yml.j2
    dest: /opt/giropops/app-v1.yml
    owner:  root 
    group:  root 
    mode: 0644
  register: copiando_deploy_app_v1

- name: Copiando o arquivo de deployment da app v2
  template:
    src:  app-v2.yml.j2
    dest: /opt/giropops/app-v2.yml
    owner:  root 
    group:  root 
    mode: 0644
  register: copiando_deploy_app_v2

- name: Deploy da app-v2 utilizando o modulo k8s do Ansible
  k8s:
    state: present
    namespace: default
    src: /opt/giropops/app-v2.yml

- name: Scale dow da app-v1
  k8s:
    state: present
    namespace: default
    src: /opt/giropops/app-v1.yml
    
- name: Dentro de 2 min o app-v1 sera removido
  pause:
    minutes: 2

- name: Removendo app-v1
  k8s:
    state: absent
    src: /opt/giropops/app-v1.yml
