---
- name: Download do Helm
  get_url:
    url: "{{ helm_url }}"
    dest: /tmp/get_helm.sh
    mode: 0755
  ignore_errors: true
  register: download_helm

- name: Instalando o Helm
  shell:
    /tmp/get_helm.sh
  when:
    - download_helm.failed|bool ==  false
  register: install_helm

- name:
  debug:  var=install_helm
